spring.application.name=libreria
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5002/libreria
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Kafka Consumer Configuration

# ===== HTTP =====
security.http.connect-timeout=2000
security.http.response-timeout=5000
seconds.response.timeout=30